#%RAML 1.0
title: M4 Student API
version: v1

baseUri: https://localhost:8082/{version}/employee
description: Employee CRUD operation

mediaType: 
- application/json 

protocols: 
- HTTPS

/student:
  get: